/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    _AppFooter: typeof import('./components/_AppFooter.vue')['default']
    _HelloWorld: typeof import('./components/_HelloWorld.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CreateCustomer: typeof import('./components/CreateCustomer.vue')['default']
    DeleteCustomer: typeof import('./components/DeleteCustomer.vue')['default']
    FindCustomer: typeof import('./components/FindCustomer.vue')['default']
    FindSale: typeof import('./components/FindSale.vue')['default']
    FindSaleView: typeof import('./components/FindSaleView.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateCustomer: typeof import('./components/UpdateCustomer.vue')['default']
  }
}
