DROP TABLE IF EXISTS DEMO;

CREATE TABLE DEMO (
    ID INTEGER AUTO_INCREMENT,
    STR VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

INSERT INTO DEMO VALUES(default, '磐長谷 詩月');
INSERT INTO DEMO VALUES(default, 'poeMoon0416');
INSERT INTO DEMO VALUES(default, '偏在するゲスト');
INSERT INTO DEMO VALUES(default, '永遠に終わらないテスト');

SELECT * FROM DEMO;
