USE DEMO;
SHOW DATABASES;

DROP TABLE IF EXISTS DEMO;
DROP TABLE IF EXISTS SALES;
DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS PERSONS;
CREATE TABLE DEMO (
    ID INTEGER AUTO_INCREMENT,
    STR VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);
CREATE TABLE CUSTOMERS (
    ID INTEGER AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);
CREATE TABLE SALES (
    ID INTEGER AUTO_INCREMENT,
    PRICE INTEGER NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);
CREATE TABLE PERSONS (
    ID INTEGER AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    WEIGHT INTEGER NOT NULL,
    PROFILE VARCHAR(255) NOT NULL,
    PREFECTURE VARCHAR(255) NOT NULL,
    CREATED_DATE_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY(ID)
);
SHOW TABLES;

INSERT INTO DEMO VALUES(DEFAULT, '磐長谷 詩月');
INSERT INTO DEMO VALUES(DEFAULT, 'poeMoon0416');
INSERT INTO DEMO VALUES(DEFAULT, '偏在するゲスト');
INSERT INTO DEMO VALUES(DEFAULT, '永遠に終わらないテスト');
INSERT INTO CUSTOMERS VALUES(DEFAULT, 'ゲスト');
INSERT INTO CUSTOMERS VALUES(DEFAULT, '磐長谷');
INSERT INTO SALES VALUES(DEFAULT, 1000, 1);
INSERT INTO SALES VALUES(DEFAULT, 1500, 1);
INSERT INTO SALES VALUES(DEFAULT, 999, 2);
INSERT INTO PERSONS VALUES(DEFAULT, 'test@example.com', 60, 'テスト自己紹介です。', '大阪府', '2025-08-17 00:00:00');
SELECT * FROM DEMO;
SELECT * FROM CUSTOMERS;
SELECT * FROM SALES;
SELECT * FROM PERSONS;
